### ISSUE TITLE
Consider converting to TypeScript

### ISSUE THREAD

**Issue by matthewp** [matthewp/haunted#124]
To aid with having better typing and not accidentally messing up the existing typings, we should consider migrating to TypeScript. This is not an issue that's ready to be taken on yet, but just for discussion at the moment.

**Comment by askbeka** [comment]
Great! I am willing to help.
have you started already?

One minor issue I have faced myself consuming libraries produced by typescript compilation;
https://github.com/Polymer/lit-html/issues/986

**Comment by Gladear** [comment]
Hi @askbeka !
I'm already trying to convert Haunted to Typescript. I didn't share anything here because I was pretty sure I would not be able to do it, but things are actually better than I thought !
Still, if you can help me finish it, it would be very nice from you 😄

You can check out my work on my fork of Haunted, on the [typescript branch](https://github.com/Gladear/haunted/tree/typescript).
Things to do are mostly marked with a `TODO` comment, and there are some remaining `any` types here and there.

**Comment by matthewp** [comment]
This issue is marked as "discussion" because I still want to talk about the pros/cons of doing so. Please don't start work (unless for your own needs) yet! 😀 If we do this it will have to come after the next minor release anyways, which is in the `minor` branch currently. So converting master now will cause pain down the line.

**Comment by Gladear** [comment]
@matthewp Actually, I did it for two reasons :
- I tried to create a router for haunted, written in Typescript. It made me realize that the new types were wrong, and that they could not be used to create hooks
- I just wanted to try :stuck_out_tongue:

I did see the next minor release coming, so I used the `minor` branch as base.

As for cons, for what I already tried, the bundle size almost didn't change !
And it had pros too ! It made me see a mistake in the useState hook: `this.state` is redefined in the child hook, whilst already defined in the Hook class.

So, for now, there are only benefits :blush:

**Comment by talentlessguy** [comment]
yeah, better rewrite it in TS not to waste time on writing typings, then configuring `tsconfig` in projects....

BTW, @Gladear, how's the fork going?

**Comment by matthewp** [comment]
Haunted was converted to TS a while back.

**Comment by talentlessguy** [comment]
> Haunted was converted to TS a while back.

great! I didn't know that but at least one more issue is closed :)
