### ISSUE TITLE
Variable name in custom hook example may be misleading

### ISSUE THREAD

**Issue by chuanqisun** [matthewp/haunted#134]
In the custom hook example, you have 
```javascript
const useMyHook = hook(class extends Hook {
  constructor(id, el) {
    super(id, el);
    ...
  }

  update() { ... }

  teardown() { ... }

});
```
in which  `el` is actually the `Container`, not the element. When I saw `el`, my first impression was it's either the fragment or the host of the shadow DOM element. Would it be better to rename the variable to `container` or add some documentation on the signature for the custom hook's constructor?

This problem could also be solved once you have #133 merged, in which a new concept called `State` will replace the `Container`. But that PR will probably lead to an overhaul of the docs. I wasn't sure if doc updates are gonna be part of that PR.

**Comment by matthewp** [comment]
Yeah, this is updated in the minor branch, I noticed that too: https://github.com/matthewp/haunted/tree/minor#write-your-own-hook

The reason is originally Haunted always operated on actual elements. When virtual components were added so was containers, but `el` was never changed as the variable name in the code or examples. Now it will be though!
