### ISSUE TITLE
bundle size 

### ISSUE THREAD

**Issue by nikitapilgrim** [matthewp/haunted#80]
Why is the library size so big?
haunted - 4.9 kb with gzip 
lit-html - 3.3kb gzip/lighterhtml 5.8kb
--------------------
for comparison Preact 3.5kb
what is the advantage?

**Comment by matthewp** [comment]
Haunted includes lit-html in it's bundle size. It's a way to create components using the Hooks pattern and using lit-html for templating.

**Comment by matthewp** [comment]
If you want to compare to Preact you'd want to include Preact, preact/hooks, and htm.

**Comment by chase-moskal** [comment]
@nikitapilgrim 

> 4.9 kb with gzip *[...]* size so big?

nah mate, 5 KB is awesome :fire: 

[compare](https://gist.github.com/Restuta/cda69e50a853aa64912d) that with 

- React 16.2.0 + React DOM — `31.8K`
- Angular 2 — `111K`
- Vue 2.4.2 — `20.9K`

**Comment by nikitapilgrim** [comment]
5kb is a lot for this functionality. It is necessary to remove the lit-html, as a dependency. If we consider that the library implements the hooks for the standard web components and hyperHTML or lit-html. Is it possible Reduce the weight of the library by 60% +

**Comment by nikitapilgrim** [comment]
> @nikitapilgrim
> 
> > 4.9 kb with gzip _[...]_ size so big?
> 
> nah mate, 5 KB is awesome 🔥
> 
> [compare](https://gist.github.com/Restuta/cda69e50a853aa64912d) that with
> 
> * React 16.2.0 + React DOM — `31.8K`
> * Angular 2 — `111K`
> * Vue 2.4.2 — `20.9K`
Invalid categories for comparison. I propose to compare with
Omi.js - 7K
Rax.js - 7.1K
Preact - 3.5-4K
Hyperapp - 1-2K

**Comment by chase-moskal** [comment]
> 5kb is a lot for this functionality

why do you think so?

> Is it possible Reduce the weight of the library by 60%

i don't think that's necessary, why is that important when it's already so tiny?

> It is necessary to remove the lit-html, as a dependency.

i agree, haunted should be render engine agnostic, or at least allow us to control which version of lit-html is being used

> As far as I understand, I can use the library, both with standard components, and with lit-html and hyperhtml. Then why do I need a lit-html dependency if I will not use it?

i think your question is, "how do i use hyperhtml instead of lit-html?"

i think hyperhtml is a feature enhancement that should be added, see #66

**Comment by chase-moskal** [comment]
> Omi.js - 7K
> Rax.js - 7.1K
> Preact - 3.5-4K
> Hyperapp - 1-2K

haunted is very comparable to these other tiny libraries, i don't get what the problem appears to be?

@nikitapilgrim — are you sure you're not beginning to micro-optimize?

**Comment by matthewp** [comment]
Preact is not comparable in functionality. You want Preact + preact/hooks + htm.

**Comment by nikitapilgrim** [comment]
I am writing cloud computing. Functions are limited in weight, additional code execution time === higher cash costs. 
Thanks for the library. If I have free time, I can help with optimization.

**Comment by chase-moskal** [comment]
@nikitapilgrim 

> I am writing cloud computing. Functions are limited in weight, additional code execution time === higher cash costs.

on the clientside, cdn servcies like unpkg or jsdelivr are willing to pay the bills for you: just load haunted (and anything else) via https://unpkg.com/haunted@4.2.1/index.js

on the serverside, you're running a whole node runtime and all of the libraries associated with that, i think haunted would surely be the smallest piece of the puzzle... i don't have experience writing these new highfalutin' cloud functions, so perhaps there's something i'm not understanding?

i strongly suggest that for your use-case, don't use the haunted bundles, instead, reference each module individually, to avoid loading any unused code

so instead of doing this:

```js
import {component, html} from "https://unpkg.com/haunted@4.2.1/index.js"
```

do this instead:

```js
import {component} from "https://unpkg.com/haunted@4.2.1/src/component.js"
import {html} from "https://unpkg.com/haunted@4.2.1/src/lit.js"
```

> Thanks for the library. If I have free time, I can help with optimization.

awesome! if you follow my above advice of loading each module individually, then a worthwhile optimization would be to generate minified versions of each module individually

there could be an build step that uses uglify to generate a `dist/` directory which contains a minified version of each module

@matthewp — what are your thoughts on such an optimization?

of course, a totally alternative pathway would be to continue using the haunted bundle, but to use rollup and uglify in your own development process, and then you're using rollup's tree-shaking to avoid unwanted code instead of direct module references

**Comment by matthewp** [comment]
I'm not sure there's a huge market for minified builds of libraries any more, almost everyone does that themselves in their own build system. If you are using Haunted through unpkg you're probably deploying to an environment where the savings aren't super important anyways. I'd prefer not to further complicate the already complicated build process we have.

**Comment by matthewp** [comment]
Closing in favor of #95 and #102 which will:

1. Add bundle size info to the readme.
2. Add `haunted/core` so that you can use a different view library.
