### ISSUE TITLE
Benefits of virtual?

### ISSUE THREAD

**Issue by stevenvachon** [matthewp/haunted#96]
I'm not sure what the advantage of:
```js
const v = virtual(text => html`<b>${text}</b>`);
```

…is over:
```js
const v = text => html`<b>${text}</b>`;
```

…when used in this context:
```js
const App = ({name}) => html`Hello ${v(name)}!`;
App.observedAttributes = ['name'];
customElements.define('my-app', component(App));

document.body.innerHTML += `<my-app name="asdf"></my-app>`;
```

**Comment by matthewp** [comment]
I don't use it personally, I think one of the main reasons people like it is to avoid the web component polyfills. And not creating an element in the tree. But you're right that a function serves the latter purpose and can even have its own hook.

Maybe @askbeka would like to chime in here with other reasons.

**Comment by jpray** [comment]
@matthewp, I believe the bugs with virtual components are still unresolved.  If you are on the verge of a major release, then it might be worth considering removing that feature from haunted, unless you think the issues can be fixed.

**Comment by matthewp** [comment]
I think we're not going to do a major release, the new build stuff can go in a minor. People do like the virtual feature so I'd like to try and resolve the problems before giving up on it.

**Comment by stevenvachon** [comment]
I still don't understand its benefits, though.

**Comment by matthewp** [comment]
@stevenvachon Do you want to discuss more? I attempted to give you some reasons above but you did not respond.

Going to close this issue for now as I don't think there's anything actionable.

**Comment by stevenvachon** [comment]
You described a benefit that is common to both `virtual()` and a function, not one that differentiates the two, supporting the existence of `virtual()`.

**Comment by askbeka** [comment]
@stevenvachon Yuo can take look at [original request](https://github.com/matthewp/haunted/issues/27) for virtual components, it might help to understand the motivation.

Since then I have written bunch of WC and applications based on WC at scale, and most painful part is that `customElements.define(name, class)`, it makes it hard to build applications in distributed teams, in "microfrontends" fashion, since you cannot have multiple versions of the same element defined on the page, teams working on different parts of application have to align in versions, which limits their independence.

With [scoped registries](https://gist.github.com/justinfagnani/d67d5a5175ec220e1f3768ec67a056bc) might solve it, but it is [far from ready](https://github.com/w3c/webcomponents/issues/716)

**Comment by askbeka** [comment]
@stevenvachon And you cannot have functions rendering conditionally if they contain hooks
```js
html`<p>${decide ? FuncA() : FunctB()}</p>`
```
because of [this](https://reactjs.org/docs/hooks-rules.html)
